#!/bin/bash

# Shared by direct TIME run scripts and scheduler wrappers.
runtime_project_root="${PROJECT_ROOT:-${ROOT_DIR:?ROOT_DIR or PROJECT_ROOT must be set}}"

TIME_STORAGE_ROOT="${TIME_STORAGE_ROOT:-$runtime_project_root}"
TIME_DATA_ROOT="${TIME_DATA_ROOT:-$TIME_STORAGE_ROOT/datasets}"
TIME_DATASET="${TIME_DATASET:-$TIME_DATA_ROOT/hf_dataset}"
TIME_METADATA="${TIME_METADATA:-$TIME_DATA_ROOT/time_metadata}"
TIME_WEIGHTS="${TIME_WEIGHTS:-$TIME_STORAGE_ROOT/weights}"
OUTPUTS_ROOT="${OUTPUTS_ROOT:-${TIME_OUTPUTS:-$runtime_project_root/outputs}}"
LOGS_ROOT="${LOGS_ROOT:-${TIME_LOGS:-$runtime_project_root/logs}}"
TIME_OUTPUTS="$OUTPUTS_ROOT"
TIME_LOGS="$LOGS_ROOT"

HF_HOME="${HF_HOME:-$TIME_WEIGHTS/huggingface}"
HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-$HF_HOME/hub}"
HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-$HF_HOME/datasets}"
TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$HF_HOME/transformers}"
TORCH_HOME="${TORCH_HOME:-$TIME_WEIGHTS/torch}"

export TIME_STORAGE_ROOT TIME_DATA_ROOT TIME_DATASET TIME_METADATA TIME_WEIGHTS
export OUTPUTS_ROOT LOGS_ROOT TIME_OUTPUTS TIME_LOGS
export HF_HOME HUGGINGFACE_HUB_CACHE HF_DATASETS_CACHE TRANSFORMERS_CACHE TORCH_HOME

mkdir -p "$TIME_DATA_ROOT" "$TIME_METADATA" "$TIME_WEIGHTS" "$TIME_OUTPUTS" "$TIME_LOGS"
